#!/bin/bash
# {author: Paulo Jeronimo; email: paulojeronimo@gmail.com; twitter: @paulojeronimo}
set +x

BASEDIR=`cd "$(dirname "$0")"; echo -n $PWD`
LOCAL=../.`basename "$BASEDIR"`/middleman-server
OP=$1

cd $BASEDIR

local_created=false
if [ ! -f $LOCAL ]
then
    mkdir -p "`dirname "$LOCAL"`"
    cat > $LOCAL <<'EOF'
cd /vagrant
set -x
bundle install
bundle exec middleman server
EOF
    local_created=true
fi

chmod +x $LOCAL

if [ $USER = vagrant ]
then
    bash $BASEDIR/$LOCAL
else
    BASEDIR=/vagrant/.`basename "$BASEDIR"`
    LOCAL=`basename "$LOCAL"`
    if [ "$OP" = "stop" ]
    then
        echo "Matando processos ruby em execução na box ..."
        vagrant ssh -c 'pkill ruby'
    else
        echo "Solicitando a execução do Middleman para o teu projeto ..."
        vagrant ssh -c $BASEDIR/$LOCAL
    fi
fi

if $local_created
then
    echo "Removendo o script temporário ($BASEDIR/$LOCAL) ..."
    rm -f $LOCAL
fi
