#!/bin/bash
# {author: Paulo Jeronimo; email: paulojeronimo@gmail.com; twitter: @paulojeronimo}
set +x

BASEDIR=`cd "$(dirname "$0")"; echo -n $PWD`
LOCAL=../.`basename "$BASEDIR"`/middleman-server
OP=$1

cd $BASEDIR

if [ ! -f $LOCAL ]
then
    tmp_middleman_server=/tmp/middleman_server.$$
    cat > $tmp_middleman_server <<'EOF'
cd /vagrant
set -x
bundle install
bundle exec middleman server
EOF
    if [ $USER = vagrant ]
    then
        mkdir -p "`dirname "$LOCAL"`"
        mv $tmp_middleman_server $LOCAL
        chmod +x $LOCAL
    else
        cat $tmp_middleman_server | vagrant ssh -c "
d=/vagrant/.`basename "$BASEDIR"`
mkdir \$d && cd \$d
cat - > middleman-server
chmod +x middleman-server
        "
    fi
fi

if [ $USER = vagrant ]
then
    bash $BASEDIR/$LOCAL
else
    BASEDIR=/vagrant/.`basename "$BASEDIR"`
    LOCAL=`basename "$LOCAL"`
    if [ "$OP" = "stop" ]
    then
        echo "Matando processos ruby em execução na box ..."
        vagrant ssh -c 'pkill ruby'
    else
        echo "Solicitando a execução do Middleman para o teu projeto ..."
        vagrant ssh -c $BASEDIR/$LOCAL
    fi
fi
